linters:
  enable-all: true
  disable:
    - depguard
    - dogsled
    - errchkjson
    - exhaustivestruct
    - exhaustruct
    - forcetypeassert
    - gci
    - gochecknoglobals
    - gochecknoinits
    - godox
    - goerr113
    - gofumpt
    - ireturn
    - nonamedreturns
    - paralleltest
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl

linters-settings:
  dupl:
    threshold: 200
  cyclop:
    max-complexity: 12
  funlen:
    lines: 80
    statements: 50
  godot:
    scope: all
  gomnd:
    ignored-numbers:
      - "2"
      - "4"
      - "5"
      - "8"
      - "10"
      - "16"
      - "32"
      - "60"
      - "64"
      - "100"
  gosec:
    excludes:
      - G404
  govet:
    disable:
      - composites
  lll:
    line-length: 140
